name: binance_dart_sdk
packages:
  - packages/*
  - examples/*

scripts:
  analyze:
    run: melos exec -- "dart analyze"
    description: Run dart analyze for all packages.

  test:
    run: melos exec --dir-exists="test" -- "dart test"
    description: Run dart tests for all packages.

  version:
    run: melos version --yes
    description: Bump versions and generate changelogs using Conventional Commits.

  publish:
    run: melos publish --yes
    description: Publish all packages to pub.dev.

  format:
    run: melos exec -- "dart format ."
    description: Run dart format for all packages.

  format:check:
    run: melos exec -- "dart format --output=none --set-exit-if-changed ."
    description: Check dart format for all packages.
