name: ash_binance_api_core_example
resolution: workspace
description: Example for ash_binance_api_core.
publish_to: none

environment:
  sdk: ">=3.11.5 <4.0.0"

dependencies:
  ash_binance_api_core: ^0.1.1+2
  http: ^1.2.0
dev_dependencies:
  lints: ^5.0.0
