# path: binance_dart_sdk/packages/binance_spot/pubspec.yaml

name: binance_spot
description: Cobertura completa del API de Binance Spot (REST y WebSockets).
version: 0.1.0
resolution: workspace
repository: https://github.com/Informatica-ASHware/binance_dart_sdk
issue_tracker: https://github.com/Informatica-ASHware/binance_dart_sdk/issues

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  binance_core: any        # workspace member
  http: any
  meta: any

dev_dependencies:
  test: any
  mocktail: any
  very_good_analysis: any
  glados: any
