# path: binance_dart_sdk/packages/binance_core/pubspec.yaml

name: binance_core
description: Primitivas y transporte base para binance_dart_sdk.
version: 0.1.0
resolution: workspace
repository: https://github.com/Informatica-ASHware/binance_dart_sdk
issue_tracker: https://github.com/Informatica-ASHware/binance_dart_sdk/issues

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  cryptography: any        # versión inyectada desde el root
  http: any
  meta: any
  pointycastle: any
  web_socket_channel: any

dev_dependencies:
  test: any
  mocktail: any
  very_good_analysis: any
  glados: any
