name: binance_mock_server
description: Mock server for Binance API testing.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_web_socket: ^2.0.0
  web_socket_channel: ^3.0.1

dev_dependencies:
  http: ^1.2.0
  test: ^1.24.0
  very_good_analysis: ^6.0.0
