name: binance_futures
description: Cobertura completa del API de Binance USD-M Futures (REST y WebSockets).
version: 0.1.0
repository: https://github.com/Informatica-ASHware/binance_dart_sdk
issue_tracker: https://github.com/Informatica-ASHware/binance_dart_sdk/issues

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  binance_core: ^0.1.0
  http: ^1.2.0
  meta: ^1.10.0

dev_dependencies:
  mocktail: ^1.0.5
  test: ^1.24.0
  very_good_analysis: ^6.0.0
